name: build.yml
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
              java-version: '11'
              distribution: 'zulu'

        - name: Check code style
          run: mvn formatter:validate

        - name: Build with maven
          run: mvn clean install
